name: Build and Test

on: 
  workflow_dispatch:
  push:
    paths:
      - "src/Transmitly.Microsoft.Extensions.DependencyInjection/**"
jobs:
  build_test_deploy_template_engine:
    uses: transmitly/transmitly/.github/workflows/build-and-deploy-general-extension.yml@main
    with: 
      projectName: Transmitly.Microsoft.Extensions.DependencyInjection
      runTests: true
    secrets: inherit
